### ISSUE TITLE
fsGroup Parameter did not work on lightbits storage

### ISSUE THREAD

**Issue by ebbo-k** [metal-stack/duros-controller#39]
if you deploy a statefulset with volumes, the fsGroup parameter dont apply on lightbits storage. Local csi-lvm storage uses the fsGroup parameter and new added files where given the group-id. On lightbits-storage the normal user group is used instead of the fsGroup.

**Comment by ebbo-k** [comment]
to verify:
deploy the following statefullset with 
1. storageClassName: partition-silver
2. storageClassName: csi-lvm
change into the pod and do the following statement:
touch /usr/share/nginx/html/test.html
ls -lhd /usr/share/nginx/html/test.html

Testdeployment:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test1
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: test1
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        fsGroup: 33 
      serviceAccountName: statefulset-test
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: partition-silver
      #storageClassName: csi-lvm 
      resources:
        requests:
          storage: 1Gi
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-statefulset-test
spec:
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  privileged: false  # Don't allow privileged pods!
  allowedHostPaths:
  - pathPrefix: /etc/hosts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulset-test
  namespace: test1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-statefulset-test
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-statefulset-test 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-statefulset-test
roleRef:
  kind: Role
  name: role-statefulset-test
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: statefulset-test 
    namespace: test1

```
